services:
  # --- BACKEND: FASTAPI ---
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      database:
        condition: service_healthy
    env_file:
      # arrega as variáveis globais da raiz (.env) (se houver alguma)
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  # --- DATABASE: POSTGIS (Essencial para seu projeto) ---
  database:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgis_db
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-template}
      - POSTGRES_DB=${DB_NAME:-template}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-template}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # --- PGADMIN (Pode manter, é ótimo para DBA) ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin123}
    ports:
      - '8080:80'
    depends_on:
      database:
        condition: service_healthy # Garante que o pgAdmin só tente conectar quando o banco subir
    networks:
      - app-network

  # --- FRONTEND: VITE/REACT ---
  frontend:
    build:
      context: ./frontend      # Aponta para a pasta do frontend
      dockerfile: Dockerfile.dev
    container_name: vite_frontend
    ports:
      - "5173:5173" # Mapeamento para acesso via localhost:5173
    volumes:
      # Mapeamento do código para Hot Reload (HMR)
      - ./frontend:/app
      - /app/node_modules       
    env_file:
      # 1. Carrega as variáveis do frontend/.env (públicas)
      - ./frontend/.env
    environment:
      # Sobrescreve a URL da API para usar o endereço interno do Docker (http://<nome_do_serviço>:<porta_interna>)
      # - VITE_API_URL=http://app:3000/api
      # Sobrescreve para garantir que o navegador aponte para a porta certa do Host
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
